/**
 * GENERATED — do not edit.
 *
 * Sourced from `api/openapi.json` (the FastAPI schema snapshot). Re-run
 * `bash web/scripts/gen-types.sh` after refreshing the snapshot:
 *
 *   uv run --extra web python -c "from api.main import app; import json;
 *       print(json.dumps(app.openapi(), indent=2, sort_keys=True))" > api/openapi.json
 *   bash web/scripts/gen-types.sh
 *
 * Consumers: import the `components` namespace and pick a schema by name —
 *   import type { components } from "@/lib/api-schema";
 *   type Visualization = components["schemas"]["Visualization"];
 *
 * E.W8 T-E2 — retires the hand-mirrored types at `web/src/lib/types.ts`
 * (the hand-mirror class of bug is closed structurally; the FastAPI
 * Pydantic models are the canonical source of truth).
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit
         * @description Paginated, filterable audit log.
         */
        get: operations["list_audit_api_admin_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/flagged": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Flagged
         * @description List flagged visualizations, cursor-paginated over the converged entity.
         *
         *     The flag stream (``flags``, keyed by ``content_hash``) is grouped per entity
         *     and joined to live ``visualizations``; pagination rides ``cursors.paginate``
         *     newest-first (§0 SOTA-1). Soft-deleted rows are excluded.
         */
        get: operations["list_flagged_api_admin_flagged_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Stats
         * @description Aggregate visualization and storage statistics (over the converged entity).
         */
        get: operations["admin_stats_api_admin_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description Paginated user list with search and entry counts (over ``visualizations``).
         */
        get: operations["list_users_api_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch Users
         * @description Batch delete/suspend/unsuspend users (CRUD-CONTRACT §7 ``batch_*``).
         */
        post: operations["batch_users_api_admin_users_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/prune-empty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prune Empty Users
         * @description Delete users that own zero visualizations.
         */
        post: operations["prune_empty_users_api_admin_users_prune_empty_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete User
         * @description Cascade-delete a user and all their data (CRUD-CONTRACT §7 ``delete_user``).
         */
        delete: operations["delete_user_api_admin_users__slug__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{slug}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set User Status
         * @description Set user status to active or suspended (CRUD-CONTRACT §7 suspend/unsuspend).
         */
        post: operations["set_user_status_api_admin_users__slug__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Verify
         * @description Verify admin token is valid.
         */
        get: operations["admin_verify_api_admin_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/visualizations/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch Visualizations
         * @description Batch delete/feature/unfeature visualizations by slug (CRUD-CONTRACT §7 ``batch_*``).
         *
         *     The request shape's ``hashes`` field carries visualization **slugs** under
         *     the converged identity. ``delete`` is a soft-delete (§5).
         */
        post: operations["batch_visualizations_api_admin_visualizations_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/visualizations/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Visualization
         * @description Moderate-delete a visualization (CRUD-CONTRACT §5 / §7).
         *
         *     Default is a soft-delete (``deleted_at`` write, restorable within grace).
         *     ``?hard=true`` is the admin grace-bypass for illegal content (§7) — a true
         *     hard-delete in one operation. Both write an ``admin_audit`` row.
         */
        delete: operations["delete_visualization_api_admin_visualizations__slug__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/visualizations/{slug}/flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Dismiss Flags
         * @description Dismiss all flags for a visualization (CRUD-CONTRACT §7 ``dismiss_flags``).
         *
         *     Resolves the entity by slug, then clears the flag stream keyed by its
         *     ``content_hash`` (the ``flags`` collection's FK to the visualization's
         *     content hash). Idempotent — dismissing already-clear flags is a 200 with
         *     ``dismissed: 0``.
         */
        delete: operations["dismiss_flags_api_admin_visualizations__slug__flags_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/visualizations/{slug}/tier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Tier
         * @description Set the admin-curation tier for a visualization (CRUD-CONTRACT §7 ``feature``).
         *
         *     Guarded by an ``If-Match`` ETag (§0 SOTA-2): a stale precondition is a 412
         *     ``urn:contract:etag-mismatch``. Idempotent — re-setting the same tier is a 200.
         */
        put: operations["set_tier_api_admin_visualizations__slug__tier_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Contour */
        post: operations["save_contour_api_contours_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contours/{contourHash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contour Endpoint */
        get: operations["get_contour_endpoint_api_contours__contourHash__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contours/{contourHash}/compute/bases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute Bases */
        post: operations["compute_bases_api_contours__contourHash__compute_bases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contours/{contourHash}/compute/epicycles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute Epicycles */
        post: operations["compute_epicycles_api_contours__contourHash__compute_epicycles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/equations/compute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compute Equation
         * @description Compute closed-form Fourier series for a user-supplied f(x).
         *
         *     Tries three tiers:
         *       1. Symbolic integration (exact)
         *       2. Sequence identification (conjectured)
         *       3. Spline approximation (approximate)
         */
        post: operations["compute_equation_api_equations_compute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/equations/simplify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simplify Coefficients
         * @description Simplify existing DFT coefficients for display overlay.
         */
        post: operations["simplify_coefficients_api_equations_simplify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gallery/cursor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Public Gallery
         * @description Public gallery list — a ``visibility="public"`` alias over ``visualizations``.
         *
         *     Read-only, anonymous-permissible, cursor-paginated (CRUD-CONTRACT §0 SOTA-1,
         *     §4). The canonical path is ``GET /api/visualizations``; this alias is kept so
         *     the pre-migration frontend keeps loading until B.W4 re-points it.
         */
        get: operations["list_public_gallery_api_gallery_cursor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Image */
        post: operations["upload_image_api_images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/by-hash/{sha256}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image By Hash */
        get: operations["get_image_by_hash_api_images_by_hash__sha256__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{imageSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image Metadata */
        get: operations["get_image_metadata_api_images__imageSlug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{imageSlug}/blob": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image Blob */
        get: operations["get_image_blob_api_images__imageSlug__blob_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{imageSlug}/extract-contour": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract Contour */
        post: operations["extract_contour_api_images__imageSlug__extract_contour_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{imageSlug}/overlay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Image Overlay
         * @description Serve the image resized to match contour extraction dimensions.
         *
         *     The returned image is in the same pixel space that contour coordinates
         *     were extracted from, enabling pixel-perfect overlay alignment.
         */
        get: operations["get_image_overlay_api_images__imageSlug__overlay_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{imageSlug}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image Thumbnail */
        get: operations["get_image_thumbnail_api_images__imageSlug__thumbnail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create a new anonymous user and session.
         */
        post: operations["register_api_sessions_post"];
        /**
         * Logout
         * @description Delete the current session.
         */
        delete: operations["logout_api_sessions_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login by slug — creates a new session for an existing user.
         */
        post: operations["login_api_sessions_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return current user info.
         */
        get: operations["me_api_sessions_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visualizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Visualizations
         * @description List visualizations with cursor pagination (CRUD-CONTRACT §0 SOTA-1, §4).
         *
         *     Anonymous / default: only ``visibility=public`` live rows. ``?owner=me``
         *     (with a session) returns the caller's rows in all three visibility states.
         */
        get: operations["list_visualizations_api_visualizations_get"];
        put?: never;
        /**
         * Create Visualization
         * @description Publish a new visualization. Anonymous publish is forbidden (§3 → 401).
         */
        post: operations["create_visualization_api_visualizations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visualizations/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Visualization
         * @description Read a single visualization by slug.
         *
         *     ``draft`` rows are visible to the owner only (non-owners get 404, not 403 —
         *     refuses to confirm existence, §4). Soft-deleted rows read 404 to anonymous
         *     callers and to non-owners.
         */
        get: operations["get_visualization_api_visualizations__slug__get"];
        put?: never;
        post?: never;
        /**
         * Delete Visualization
         * @description Owner-bound soft-delete guarded by an ``If-Match`` ETag (§5).
         */
        delete: operations["delete_visualization_api_visualizations__slug__delete"];
        options?: never;
        head?: never;
        /**
         * Update Visualization
         * @description Owner-bound partial update guarded by an ``If-Match`` ETag (§3, §0 SOTA-2).
         */
        patch: operations["update_visualization_api_visualizations__slug__patch"];
        trace?: never;
    };
    "/api/visualizations/{slug}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Visualization
         * @description Restore a soft-deleted visualization within the grace window (§5).
         */
        post: operations["restore_visualization_api_visualizations__slug__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminStatsResponse */
        AdminStatsResponse: {
            /** Featured */
            featured: number;
            /** Normal */
            normal: number;
            /** Saved */
            saved: number;
            /** Storage Bytes */
            storage_bytes: number;
            /** Total Entries */
            total_entries: number;
            /** Total Likes */
            total_likes: number;
            /** Total Views */
            total_views: number;
        };
        /** AnimationSettings */
        AnimationSettings: {
            /**
             * Active Bases
             * @default [
             *       "fourier-epicycles"
             *     ]
             */
            active_bases: string[];
            /**
             * Duration
             * @default 30
             */
            duration: number;
            /**
             * Easing
             * @default sine
             */
            easing: string;
            /**
             * Fps
             * @default 30
             */
            fps: number;
            /**
             * Max Circles
             * @default 80
             */
            max_circles: number;
            /**
             * Speed
             * @default 1
             */
            speed: number;
        };
        /** BatchGalleryRequest */
        BatchGalleryRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "delete" | "feature" | "unfeature";
            /** Hashes */
            hashes: string[];
        };
        /** BatchUsersRequest */
        BatchUsersRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "delete" | "suspend" | "unsuspend";
            /** Slugs */
            slugs: string[];
        };
        /** Body_upload_image_api_images_post */
        Body_upload_image_api_images_post: {
            /** File */
            file: string;
        };
        /** ComputeBasesRequest */
        ComputeBasesRequest: {
            /** Levels */
            levels?: number[] | null;
            /**
             * Max Degree
             * @default 200
             */
            max_degree: number;
            /**
             * N Eval
             * @default 1000
             */
            n_eval: number;
            /**
             * N Points
             * @default 1024
             */
            n_points: number;
        };
        /** ComputeEpicyclesRequest */
        ComputeEpicyclesRequest: {
            /**
             * N Harmonics
             * @default 200
             */
            n_harmonics: number;
            /**
             * N Points
             * @default 1024
             */
            n_points: number;
        };
        /** ComputeEquationRequest */
        ComputeEquationRequest: {
            /**
             * Budget
             * @default 10
             */
            budget: number;
            /**
             * Domain End
             * @default 6.283185307179586
             */
            domain_end: number;
            /**
             * Domain Start
             * @default 0
             */
            domain_start: number;
            /** Expression */
            expression: string;
            /**
             * N Eval Points
             * @default 500
             */
            n_eval_points: number;
            /**
             * N Harmonics
             * @default 20
             */
            n_harmonics: number;
            /**
             * Notation
             * @default trig
             */
            notation: string;
        };
        /** ComputeEquationResponse */
        ComputeEquationResponse: {
            /** Coefficients */
            coefficients: components["schemas"]["FourierTermDTO"][];
            /** Effective N */
            effective_n: number;
            /** Energy Captured */
            energy_captured: number;
            /** Latex */
            latex: string;
            /** Latex Sigma */
            latex_sigma: string;
            /** Original Points */
            original_points: {
                [key: string]: number[];
            };
            /** Reconstructed Points */
            reconstructed_points: {
                [key: string]: number[];
            };
            /** Status */
            status: string;
            /** Tier */
            tier: string;
        };
        /** ComputeResult */
        ComputeResult: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** ContourSettings */
        ContourSettings: {
            /**
             * Blur Sigma
             * @default 0.5
             */
            blur_sigma: number;
            /**
             * Max Contours
             * @default 24
             */
            max_contours: number | null;
            /**
             * Min Contour Area
             * @default 0.001
             */
            min_contour_area: number;
            /**
             * Min Contour Length
             * @default 40
             */
            min_contour_length: number;
            /**
             * Ml Detail Threshold
             * @default 0.3
             */
            ml_detail_threshold: number;
            /**
             * Ml Threshold
             * @default 0.5
             */
            ml_threshold: number;
            /**
             * N Classes
             * @default 3
             */
            n_classes: number;
            /**
             * N Harmonics
             * @default 200
             */
            n_harmonics: number;
            /**
             * N Points
             * @default 1024
             */
            n_points: number;
            /**
             * Resize
             * @default 1024
             */
            resize: number;
            /**
             * Smooth Contours
             * @default 0.03
             */
            smooth_contours: number;
            /**
             * Strategy
             * @default auto
             */
            strategy: string;
        };
        /** ExtractContourRequest */
        ExtractContourRequest: {
            contour_settings?: components["schemas"]["ContourSettings"];
        };
        /** FourierTermDTO */
        FourierTermDTO: {
            /** Amplitude */
            amplitude: number;
            /** Coefficient Im */
            coefficient_im: number;
            /** Coefficient Re */
            coefficient_re: number;
            /** N */
            n: number;
            /** Phase */
            phase: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImageAssetResponse */
        ImageAssetResponse: {
            /** Bytes */
            bytes: number;
            /** Content Type */
            content_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Image Slug */
            image_slug: string;
            /**
             * Last Accessed At
             * Format: date-time
             */
            last_accessed_at: string;
            /** Original Name */
            original_name: string;
            /** Sha256 */
            sha256: string;
        };
        /** SaveContourRequest */
        SaveContourRequest: {
            /** Image Slug */
            image_slug: string;
            /** Points */
            points: {
                [key: string]: unknown;
            };
        };
        /** SetTierRequest */
        SetTierRequest: {
            /**
             * Tier
             * @enum {string}
             */
            tier: "featured" | "saved" | "normal";
        };
        /** SetUserStatusRequest */
        SetUserStatusRequest: {
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "suspended";
        };
        /** SimplifyRequest */
        SimplifyRequest: {
            /**
             * Budget
             * @default 6
             */
            budget: number;
            /** Coefficients */
            coefficients: components["schemas"]["FourierTermDTO"][];
            /**
             * Notation
             * @default trig
             */
            notation: string;
        };
        /** SimplifyResponse */
        SimplifyResponse: {
            /** Energy Captured */
            energy_captured: number;
            /** Latex */
            latex: string;
            /** Term Count */
            term_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VisualizationCreate
         * @description POST body. Server generates the slug if absent and recomputes the
         *     content hash; ``owner_slug`` is sourced from the session, never the body.
         */
        VisualizationCreate: {
            /** Active Bases */
            active_bases: string[];
            animation_settings?: components["schemas"]["AnimationSettings"] | null;
            /** Contour Hash */
            contour_hash: string;
            contour_settings?: components["schemas"]["ContourSettings"] | null;
            /** Description */
            description?: string | null;
            /** Image Slug */
            image_slug: string;
            /** N Harmonics */
            n_harmonics: number;
            /** Palette Slug */
            palette_slug?: string | null;
            /** Slug */
            slug?: string | null;
            /** Tags */
            tags?: string[];
            /** Title */
            title?: string | null;
            /**
             * Visibility
             * @default draft
             * @enum {string}
             */
            visibility: "draft" | "unlisted" | "public";
        };
        /**
         * VisualizationUpdate
         * @description PATCH body. Partial; ``slug`` is immutable and ``content_hash`` is
         *     recomputed server-side (so neither appears here).
         */
        VisualizationUpdate: {
            /** Description */
            description?: string | null;
            /** Palette Slug */
            palette_slug?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Title */
            title?: string | null;
            /** Visibility */
            visibility?: ("draft" | "unlisted" | "public") | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_audit_api_admin_audit_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                action?: string;
                after?: string;
                before?: string;
                target?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_flagged_api_admin_flagged_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_stats_api_admin_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStatsResponse"];
                };
            };
        };
    };
    list_users_api_admin_users_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                sort?: string;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_users_api_admin_users_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchUsersRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prune_empty_users_api_admin_users_prune_empty_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    delete_user_api_admin_users__slug__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_user_status_api_admin_users__slug__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetUserStatusRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_verify_api_admin_verify_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    batch_visualizations_api_admin_visualizations_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchGalleryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_visualization_api_admin_visualizations__slug__delete: {
        parameters: {
            query?: {
                hard?: boolean;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_flags_api_admin_visualizations__slug__flags_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_tier_api_admin_visualizations__slug__tier_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetTierRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_contour_api_contours_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveContourRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contour_endpoint_api_contours__contourHash__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contourHash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_bases_api_contours__contourHash__compute_bases_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contourHash: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComputeBasesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComputeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_epicycles_api_contours__contourHash__compute_epicycles_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contourHash: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComputeEpicyclesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComputeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_equation_api_equations_compute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComputeEquationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComputeEquationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simplify_coefficients_api_equations_simplify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimplifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimplifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_public_gallery_api_gallery_cursor_get: {
        parameters: {
            query?: {
                limit?: number;
                sort?: string;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    upload_image_api_images_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_image_api_images_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageAssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_by_hash_api_images_by_hash__sha256__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sha256: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageAssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_metadata_api_images__imageSlug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                imageSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageAssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_blob_api_images__imageSlug__blob_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                imageSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_contour_api_images__imageSlug__extract_contour_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                imageSlug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractContourRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_overlay_api_images__imageSlug__overlay_get: {
        parameters: {
            query?: {
                resize?: number;
            };
            header?: never;
            path: {
                imageSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_thumbnail_api_images__imageSlug__thumbnail_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                imageSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    logout_api_sessions_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_api_sessions_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    me_api_sessions_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_visualizations_api_visualizations_get: {
        parameters: {
            query?: {
                limit?: number;
                sort?: string;
                cursor?: string;
                owner?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_visualization_api_visualizations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisualizationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_visualization_api_visualizations__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_visualization_api_visualizations__slug__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_visualization_api_visualizations__slug__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisualizationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_visualization_api_visualizations__slug__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
