#!/usr/bin/env bash
# F.REL .h — production-compose boot + health: the whole production stack
# (docker-compose.yml + docker-compose.prod.yml: mongo under verified TLS + auth,
# the read-only backend, the read-only frontend and the read-only nginx edge)
# boots exactly as the host's deploy brings it up, and must answer the same two
# questions the deploy hook's gate asks, from outside the stack:
#
#   LIVENESS   GET /api/health through the edge → 200 {"status":"ok"} (json)
#   READINESS  GET /           through the edge → 404 (inv-22: the API host root)
#
# plus every service's own HEALTHCHECK reading `healthy`. A container that
# crash-loops (the H.W4 nginx cap floor did, from 2026-06 until F.REL .h) fails
# here instead of on the host. This is the CI job `prod-compose` and the local
# reproduction of the host gate; one script for both.
#
#   scripts/prod-compose-smoke.sh               # build, boot, probe, tear down
#   SKIP_BUILD=1 scripts/prod-compose-smoke.sh  # reuse the project's images
#   KEEP_UP=1 scripts/prod-compose-smoke.sh     # leave the stack running
#
# Env: PROJECT (compose project, default fourier-prod-smoke) · HTTP_PORT (the
# edge bind, default 8192) · WAIT_TIMEOUT (seconds, default 420). TLS material
# under ./ssl (gitignored) is generated by scripts/gen-mongo-certs.sh when absent.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

export COMPOSE_PROJECT_NAME="${PROJECT:-fourier-prod-smoke}"
export HTTP_PORT="${HTTP_PORT:-8192}"
export MONGO_USER="${MONGO_USER:-fourier-admin}"
export MONGO_PASSWORD="${MONGO_PASSWORD:-prod-smoke-$(od -An -N8 -tx1 /dev/urandom | tr -d ' \n')}"
WAIT_TIMEOUT="${WAIT_TIMEOUT:-420}"
COMPOSE=(docker compose -f docker-compose.yml -f docker-compose.prod.yml)
BASE="http://127.0.0.1:${HTTP_PORT}"

say() { printf '[prod-compose-smoke] %s\n' "$*"; }

dump() {
  say "FAIL — stack state and the last log lines of every service follow"
  "${COMPOSE[@]}" ps -a || true
  for svc in mongo backend frontend nginx; do
    printf '\n── %s ──\n' "$svc"
    "${COMPOSE[@]}" logs --no-color --tail 25 "$svc" 2>&1 | cut -c1-300 || true
  done
}

teardown() {
  if [[ "${KEEP_UP:-0}" == "1" ]]; then
    say "KEEP_UP=1 — the stack stays up (project ${COMPOSE_PROJECT_NAME}, edge ${BASE})"
    return
  fi
  "${COMPOSE[@]}" down -v --remove-orphans >/dev/null 2>&1 || true
  rm -f .deploy/edge/*.conf
}
trap teardown EXIT

if [[ ! -s ssl/mongo.pem || ! -s ssl/mongo-ca.pem ]]; then
  say "no ./ssl TLS material — generating it (scripts/gen-mongo-certs.sh)"
  bash scripts/gen-mongo-certs.sh >/dev/null
fi
# The edge's upstream-pin dir (the deploy hook writes it; nginx mounts it :ro).
# Created here so the daemon never creates it root-owned, and emptied: a fresh
# stack has no pins (a stale one would name a container that does not exist).
mkdir -p .deploy/edge
rm -f .deploy/edge/*.conf
# The prod overlay declares image_blobs external (the host's long-lived volume).
docker volume inspect image_blobs >/dev/null 2>&1 || docker volume create image_blobs >/dev/null

if [[ "${SKIP_BUILD:-0}" != "1" ]]; then
  say "building the production images (project ${COMPOSE_PROJECT_NAME})"
  "${COMPOSE[@]}" build
fi

say "booting the production stack (up -d --wait, ≤ ${WAIT_TIMEOUT}s)"
if ! "${COMPOSE[@]}" up -d --wait --wait-timeout "$WAIT_TIMEOUT"; then
  dump
  exit 1
fi

fail=0
unhealthy="$("${COMPOSE[@]}" ps --format '{{.Service}} {{.Health}}' | awk '$2 != "healthy" {print}')"
if [[ -n "$unhealthy" ]]; then
  say "services not healthy: ${unhealthy//$'\n'/; }"
  fail=1
fi

live_code="$(curl -sS -o /tmp/prod-smoke-health.$$ -w '%{http_code} %{content_type}' --max-time 5 "$BASE/api/health" || true)"
live_body="$(cat /tmp/prod-smoke-health.$$ 2>/dev/null || true)"
rm -f /tmp/prod-smoke-health.$$
say "LIVENESS  GET /api/health → ${live_code} ${live_body}"
[[ "$live_code" == "200 application/json"* && "$live_body" == *'"status"'*'"ok"'* ]] || fail=1

ready_code="$(curl -sS -o /dev/null -w '%{http_code}' --max-time 5 "$BASE/" || true)"
say "READINESS GET / → ${ready_code} (want 404, inv-22)"
[[ "$ready_code" == "404" ]] || fail=1

if [[ "$fail" -ne 0 ]]; then
  dump
  exit 1
fi
"${COMPOSE[@]}" ps --format '{{.Service}}: {{.Health}}' | sort | sed 's/^/[prod-compose-smoke]   /'
say "PASS"
